# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
user = CreateAdminService.new.call
puts 'CREATED ADMIN USER: ' << user.email

# Drone Models
drone_models_list = [
  "Aerix Drones  Black Talon",
  "UTO Drone U960 Hexacopter",
  "Revell-Control X-SPY 2.0 (23954)",
  "Odyssey Toys Pocket Drone",
  "Syma X5C Explorers",
  "Odyssey Toys X-7 Microlite",
  "Axis Drones Vidius",
  "Air Hogs Millenium Falcon Drone",
  "Sky Viper v950STR",
  "Mota Jetjat Nano",
  "Horizon Hobby Blade Nano QX2",
  "Parrot Airborne Cargo",
  "Parrot Airborne Night Swat ",
  "Hubsan FPV X4 H107D",
  "Parrot MiniDrone Rolling Spider",
  "TRNDLabs SKEYE Hexadrone",
  "Air Hogs Helix Ion",
  "TRNDLabs SKEYE Nano Drone",
  "Shengkai X8AMG",
  "Onagofly Nano Quadcopter",
  "Hubsan X4 H501C",
  "Syma X8G",
  "JJRC H12C",
  "WLtoys V353",
  "WLtoys V656",
  "Sky Viper V2900 Pro",
  "GPTOYS Aviax F2C",
  "JJRC H12CH",
  "Eachine Racer 130",
  "JYU Spider X",
  "Eachine H99D",
  "WebRC XDrone HD",
  "WebRC XDrone HD 2",
  "Xtreem Fly Eye",
  "HeliMax 230 Si V-Cam",
  "Huajun Move Wings W606-2",
  "Kai Deng K70C Sky Warrior",
  "Kai Deng K70F",
  "Hubsan X4 H502S",
  "Jin Xing Da 506V",
  "Huajun U-Fly W606-3",
  "Xtreem Raptor Eye",
  "SKRC D20G",
  "XK X250-A",
  "Riviera RC Night Stalker Drone HD",
  "XK X250-B",
  "Hubsan X4 H502E",
  "Lead Honor LH-X14D",
  "JJRC H27WH Firefly",
  "WLToys V666",
  "Dromida Ominus FPV",
  "WLtoys Q303-A",
  "Huajun W606-5 Flanker",
  "Feilun FX120C2",
  "Lian Sheng LS - 128 Sky Hunter",
  "WLtoys V686J - Explore",
  "WLtoys Q333 - C",
  "LiDi RC L6F",
  "Jin Xing Da 509G",
  "Lead Honor LH-X8WF",
  "SJ X300-2C",
  "JXD 510G",
  "WLtoys V606 - Explorers",
  "WLtoys Q212",
  "WLtoys V666N",
  "JJRC V686",
  "Holy Stone F181",
  "Nine Eagles  Galaxy Visitor 6 Pro",
  "Hubsan H111D Nano FPV Q4",
  "JJRC H26W",
  "JJRC H16-2 X6",
  "Holy Stone HS110W",
  "MJX X601H",
  "Helic Max Sky Hawkeye 1331S",
  "WLtoys V959 Pro - Battleship",
  "Riviera RC  Nano Cam",
  "RIviera RC Micro Quadcopter",
  "Holy Stone U818A HD+",
  "RC Leading RC111F",
  "JJRC H8D",
  "Cheerson CX-35",
  "XinLin X181",
  "JJRC V686J",
  "Holy Stone X401H-V2",
  "Yi Zhan iDrone i7H",
  "Huaxiang 8923V",
  "HeliMax 1SQ V-Cam",
  "JJRC H9D",
  "JJRC H11WH",
  "FQ777 918C",
  "GTeng T901F",
  "Archos  Drone",
  "BOJIANG S5C-2",
  "Bayangtoys X5C-1",
  "UDI RC Falcon U842",
  "Eachine E40G",
  "GTeng T902C",
  "Lead Honor  LH-X16WF",
  "Cheerwing CW4",
  "Syma X5SC-1"
]

drone_models_list.each do |model|
  DroneModel.create(model: model)
end
